name: App build
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

  workflow_dispatch:

env:
  PYTHON_VERSION: '3.13.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout code
    #   version: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests


    - name: run app
      run: |
        python app.py

      
